#!/usr/bin/bash

module use /nobackup/CESM/module_env
module load cesm

MY_CASE=b.e21.BWma1850.f19_g17.TRAPPIST1_e.no_T_lock.P19.my_case.001

$CIMEROOT/scripts/create_newcase --case $HOME/cesm_prep/$MY_CASE --compset BWma1850 --res f19_g17 --run-unsupported

cd $HOME/cesm_prep/$MY_CASE

./xmlchange OCN_TRACER_MODULES=iage # turn off ocean BGC tracers
./xmlchange OCN_CHL_TYPE=diagnostic # use satellite climatology for Chl for shortwave adsorption
./xmlchange CCSM_BGC=CO2A # turn off passing air-sea CO2 fluxes from ocean to atmosphere
./xmlchange RUN_TYPE=branch
./xmlchange GET_REFCASE=FALSE
./xmlchange RUN_REFCASE=b.e21.BWma1850.f19_g17.TRAPPIST1_e.no_T_lock.011
./xmlchange RUN_REFDATE=0262-01-10
./xmlchange NTASKS=-1
./xmlchange NTASKS_PER_INST=-1
./xmlchange NTASKS_ESP=1
./xmlchange NTASKS_PER_INST_ESP=1
./xmlchange JOB_WALLCLOCK_TIME="0:20:00"
./xmlchange STOP_OPTION="ndays"
./xmlchange STOP_N=1
./xmlchange REST_OPTION="ndays"
./xmlchange REST_N=1
./xmlchange --force JOB_QUEUE=planet.q
./xmlchange PROJECT=planet
./case.setup

RESTART=/nobackup/Alternative_Earths/restarts/TP1_e/P19_SSPO_PI_noTL/0262-01-10/
PATH = /nobackup/Alternative_Earths/ExoCESM/CESM2.1.3/Tidally_locked_exoplanets/cases/TP_1_e_P19_PI_noTL/
USER_NL_CAM=$PATH/user_nl_cam
USER_NL_CPL=$PATH/user_nl_cpl
SrcModsCAM=$PATH/SourceMods/src.cam/
SrcModsCICE=$PATH/SourceMods/src.cice/
cp $SrcModsCICE/*F90  SourceMods/src.cice/
cp $SrcModsCAM/*F90  SourceMods/src.cam/
cp $RESTART/* /nobackup/$USER/cesm_sims/$MY_CASE/run/
cp $USER_NL_CAM .
cp $USER_NL_CPL .

./preview_run
./preview_namelists
./check_input_data
