#!/usr/bin/bash

module use /nobackup/CESM/module_env
module load cesm

MY_CASE=b.e21.BWma1850.f19_g17.PC_b_lnd.my_case.001

$CIMEROOT/scripts/create_newcase --case $HOME/cesm_prep/$MY_CASE --compset BWma1850 --res f19_g17 --run-unsupported

cd $HOME/cesm_prep/$MY_CASE

./xmlchange RUN_TYPE=branch
./xmlchange GET_REFCASE=FALSE
./xmlchange RUN_REFCASE=b.e21.BWma1850.f19_g17.ProxCenb.Sub_Stell_Land.010
./xmlchange RUN_REFDATE=0034-06-17
./xmlchange NTASKS=-1
./xmlchange JOB_WALLCLOCK_TIME="0:20:00"
./xmlchange STOP_OPTION="ndays"
./xmlchange STOP_N=1
./xmlchange REST_OPTION="ndays"
./xmlchange REST_N=1
./xmlchange --force JOB_QUEUE=planet.q
./xmlchange PROJECT=planet
./case.setup


RESTART=/nobackup/Alternative_Earths/restarts/PC_b_lnd/0034-06-17/
USER_NL_CAM=/nobackup/Alternative_Earths/ExoCESM/CESM2.1.3/Tidally_locked_exoplanets/cases/PC_b_SSPL/user_nl_cam
SrcMods=/nobackup/Alternative_Earths/ExoCESM/CESM2.1.3/Tidally_locked_exoplanets/cases/PC_b_SSPL/SourceMods/src.cam/
cp $SrcMods/chemistry.F90  $SrcMods/mo_jshort.F90  $SrcMods/mo_photo.F90  SourceMods/src.cam/ 
cp $SrcMods/mo_tgcm_ubc.F90  $SrcMods/upper_bc.F90  SourceMods/src.cam/
cp $RESTART/* /nobackup/$USER/cesm_sims/$MY_CASE/run/
cp $USER_NL_CAM .

./preview_run
./preview_namelists
./check_input_data
